[package]
name = "rsudoku-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
path = "lib.rs"

[dependencies]
enum_dispatch.workspace = true
getset.workspace = true
snafu.workspace = true
